### ISSUE TITLE
Fix build failure

### ISSUE THREAD

**Issue by alfsb** [php/doc-pl#19]
To quick fix build failure, update `reference/spl/book.xml`, removing this line with `&reference.spl.miscellaneous;`

https://github.com/php/doc-pl/blob/e54923fd34cf5e7486168cf55a3d0555d6925a62/reference/spl/book.xml#L26C1-L26C31

**Comment by Sobak** [comment]
Hi @alfsb 

thanks for giving a hint but something must have changed in the English version in the meanwhile because when I tested it a couple of days back, the build succeeded. Then I checked the mailing list and it didn't show a single build failure either.

**Comment by alfsb** [comment]
The build failures are not send to mailings anymore, unfortunately. Nor commits.

For curiosity, what fixed `doc-pl` weeks ago was a change of mine on [`doc-base`](https://github.com/php/doc-base/pull/198#issuecomment-2539973314).

**Comment by Sobak** [comment]
@alfsb ouch, thanks a lot for letting me know. That's unfortunate.
